# Generated by Django 4.0.1 on 2022-02-13 10:37

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('subject', models.TextField()),
            ],
        ),
    ]
